name: aws deployment process

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

env:
 SAMPLE: ${{ env.SAMPLE }}

jobs:
  Deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check the environment
        run: | 
          echo "choice is ${{ github.event.inputs.environment }}" / ${{ inputs.environment }}
          python RunScript.py
