name: aws deployment process

on:
  pull_request:
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       type: environment

env:
 SAMPLE: ${{ secrets.SAMPLE }}

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: 
          name: ${{ github.event.inputs.environment }}    
    steps:
      - uses: actions/checkout@v3
      - name: check the environment
        run: | 
          echo "choice is ${{ github.event.inputs.environment }}" / ${{ inputs.environment }}
          python RunScript.py
