name: aws deployment process

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Target platform for deployment
        options:
        - Development
        - Production
      
      environment:
        type: environment

env:
 PARAM: ${{ secrets.PARAM }}

jobs:
  Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: check the environment
        run: | 
          echo "choice is ${{ github.event.inputs.environment }}" / ${{ inputs.environment }}
          python RunScript.py
